name: CI/CD Pipeline

on:
  push:
    branches:
      - main   # or the branch you use for production
  pull_request:
    branches:
      - main

jobs:
  backend:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt

    - name: Run backend tests
      run: |
        pytest tests/

  frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: |
        cd notepad-frontend
        npm install

    - name: Run frontend tests
      run: |
        cd notepad-frontend
        npm test -- --ci --coverage

  deploy:
    runs-on: ubuntu-latest
    needs: [backend, frontend]  # Ensure tests are successful before deployment

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy Backend (example, could be AWS, Heroku, etc.)
      run: |
        echo "Deploying backend..."  # Add your deployment script here

    - name: Deploy Frontend (example, could be Netlify, Vercel, etc.)
      run: |
        echo "Deploying frontend..."  # Add your deployment script here
